### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by damassi** [ctrlplusb/easy-peasy#110]
Just wanted to say this lib is very well done 👌. What a great addition to the redux ecosystem. Thanks!

**Comment by ctrlplusb** [comment]
Thank you @damassi. I really appreciate you taking the time to show your appreciation. 😁

**Comment by macrozone** [comment]
also using it in new projects and it feels so natural to use it, as it has always been there!

Also upgrading to v2 right now!

**Comment by ctrlplusb** [comment]
Great, please let me know how the upgrade goes for you @macrozone and if there is any need to update the release notes to help others with it. 👍

**Comment by waynevanson** [comment]
THANK YOU THANK YOU!

You should add a `grateful` label, because we are so grateful of this. I will contribute to docs once I'm not working.

The typescript docs are absolutely phenomenal now, with only a few typos. They're clear, concise and to the point. Kudos to those who made it.

I'll be trying that new alpha now :)

**Comment by ctrlplusb** [comment]
Hey @waynevanson 

Thanks for the kinds words! I truly appreciate it.

I'm stoked to hear that the Typescript docs are useful. I had ignored the Typescript docs for too long and decided to give them a lot of overdue love. In doing the Typescript docs I came to realise the current tutorial (standard JS) is not as great as it could be either, and have been performing a full rewrite on those. I'm excited to release all the updated docs with the v3 release.
