### ISSUE TITLE
Allow batching actions

### ISSUE THREAD

**Issue by cevr** [ctrlplusb/easy-peasy#119]
Every action called in a model triggers a rerender, which can cause major problems with performance depending on the app.  Redux was facing this problem with their v6 iteration and are trying to fix it for v7.

https://github.com/reduxjs/react-redux/issues/1177#issuecomment-472063076

Part of their solution was to provide the API that react gives that allows for updates to be batched. 

```js
const model = {
  someThunk: thunk(
        async actions => {
            const request = {//stuff}
            const { data } = await API.post(ROWS, request);

            actions.someAction1(data.items);
            actions.someAction2(data.stuff)
            actions.setLastRequest(request);
            // these will cause three rerenders
        }
}
```
Optimized:
```js
const model = {
  someThunk: thunk(
        async actions => {
            const request = {//stuff}
            const { data } = await API.post(ROWS, request);

            batch(() => {
              actions.someAction1(data.items);
              actions.someAction2(data.stuff)
              actions.setLastRequest(request);
              // these will cause one rerender
            })
        }
}
```

**Comment by ctrlplusb** [comment]
Hey @cevr;

I did consider this already and would still be open to it.

That being said, have you tried [React concurrent mode](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-q2-2019-the-one-with-concurrent-mode)? I run it in my app and it essentially does the batching at the render level. I saw insane performance improvements, especially in areas where a large amount of concurrent actions are fired.

According to the React blog the concurrent rendering is scheduled for Q2 2019 - so soon hopefully. 😀

**Comment by cevr** [comment]
Hi @ctrlplusb 👋 

That's really interesting. Could you show me an example of how you would integrate the scheduler with easy-peasy?

As an aside, this library is really awesome and I'm digging some of the patterns I can do with it. Thanks for your hard work, and I hope to help however I can 😃

**Comment by ctrlplusb** [comment]
FYI have you looked at a middleware/enhancer based solution?

e.g.

https://github.com/tappleby/redux-batched-subscribe

**Comment by cevr** [comment]
That seems interesting.. I can't figure out how I would integrate it with this store. Would it be placed in the reducerEnhancer property of the createStore config object?

**Comment by ctrlplusb** [comment]
Hmm, we are restricted it seems.

I need to add a new config option to allow you to pass in additional store enhancers here:
https://github.com/ctrlplusb/easy-peasy/blob/5022d1c571374533193300d9c4ce8f300913e249/src/create-store.js#L110

**Comment by ctrlplusb** [comment]
See #121

**Comment by ctrlplusb** [comment]
@cevr - v2.1.0 allows this via the `enhancers` config item to `createStore`

**Comment by cevr** [comment]
@ctrlplusb Wow! Thank you 😃

**Comment by mfbx9da4** [comment]
In my particular case, batched subscribe doesn't really help. I have two stores, where store A references items in store B. When I delete items from store B, react rerenders before I can update store A to also delete the referenced items.

Example:

I have a feed. The feed is made up of different types of items. Each type of item is stored in its respective store.
The feed order is stored as an array of item IDs, referencing the items in their different substores.

I have made a minimal failing example here. The issue occurs after clicking the button three times

https://codesandbox.io/s/deleting-referenced-items-kmw1e

The key line is 

```
else console.error(">>>> feed order contains deleted item", id);
```

It's problematic that the feed order might contain deleted items.

Is there a way I might be able to batch the `createAndDeleteTodo`, to not evaluate all listeners until the entire thunk and all subthunks have completed?

As a side question, I don't see why the listener is evaluated any time a thunk is started or completed since thunks alone can never change state.
