### ISSUE TITLE
can easy-peasy be used with web components or lit-element?

### ISSUE THREAD

**Issue by chase-moskal** [ctrlplusb/easy-peasy#148]
just wondering if easy-peasy is coupled with react, or if perhaps we can work with web components and fancy template rendering like lit-html

**Comment by ctrlplusb** [comment]
I've included React bindings as default as that's where my heart is. I like my open source to be closely aligned with what I use otherwise I feel like I won't maintain it. I use my libraries so am forced to keep them up to date and big free.

You could in theory use the output of createStore (which is just a redux store), and if there are redux bindings for web components or lit element then you could provide this store to the bindings. This should be fine as the implementation won't complain or require react. The first part of the tutorial in the readme shows how to.interact with the store.

Feel free to create a fork that rips out the React based APIs 👍

Would appreciate any feedback on your efforts if you do try. 👍
