### ISSUE TITLE
Typescript breaks in nested models / state scope in action() & select()

### ISSUE THREAD

**Issue by bentron2000** [ctrlplusb/easy-peasy#158]
Hey there @ctrlplusb 

I am refactoring my state to be more nested to make it clearer to use, and I have come across an issue which I've outlined in [this codesandbox](https://codesandbox.io/embed/wyzv7z8m8w)

When using nested models, the state argument in the action seems to get typing for the incorrect scope, OR, the scope isn't what it should be.

```
export interface StuffModel {
  thing: string;
  addThing: Action<StuffModel, string>;
  nestedThing: {
    egg: string;
    setEgg: Action<StuffModel, string>;
  };
  strangeThing: {
    cuckoo: string;
    setCuckoo: Action<StuffModel, string>;
  };
}

const stuff: StuffModel = {

  // WORKS
  thing: '',
  addThing: action((state, payload) => {
    state.thing = payload;
  }),

  // DOESN'T WORK
  nestedThing: {
    egg: '',
    setEgg: action((state, payload) => {
      state.nestedThing.egg = payload; // I wish I could do this (see note below)
    })
  },

  // WORKS BUT GIVES TYPESCRIPT ERROR
  strangeThing: {
    cuckoo: '',
    setCuckoo: action((state, payload) => {
      state.cuckoo = payload; // <-- note this error!
    })
  }
};

export default stuff;

```

It would be great to be able to use state from anywhere in the tree in actions like this.
(This also holds true for `select` - I've put some examples in the code sandbox - uncomment appropriate lines to see it explode)
Being able to access global state in selectors would be amazing...

Am I doing something wrong with this approach?

Thanks again for the great library. I love it :) Cheers B

**Comment by bentron2000** [comment]
Apologies @ctrlplusb - I have made it work like so:
```
interface NestedPart {
    egg: string;
    setEgg: Action<NestedPart, string>;
}

export interface StuffModel {
  nestedThing: NestedPart;
}
```
It would still be super handy to use select on global state though :P 
Cheers
b

**Comment by ctrlplusb** [comment]
Hey @bentron2000;

Yeah, this is by design. It's a trade off with the API decisions I have made.

The rule of thumb is to consider that every object introduced into your state is in fact it's own scoped model.

Therefore for the helpers (select, thunk, action etc), all have to be applied on an interface without nesting. 

Personally, I haven't had much friction with this myself. The solution you provide in your comment above seems to work everywhere.

> Being able to access global state in selectors would be amazing

Yeah, there are tradeoffs here, unfortunately. If I allowed global state to be accessible within selectors then I am forced to run every selector for any state change. At the moment we provide an optimisation where selectors only get run when the state within their namespace changes. 

If you need a selector to access multiple namespaces of models then lift the selector up your tree, however, try to minimise this as it will have to run for every change to its namespace. For very simple selectors, or where writes are minimal, this may not be an issue - but good to be aware of this.

**Comment by bentron2000** [comment]
Thanks @ctrlplusb, 
I get you - makes sense.
Having thought about this a bit more, it seems quite straightforward to nest things away and lift selectors up the tree just enough to work as needed.
Your response has made things a lot clearer - I might add a pull request on the docs and see if it helps others.

Thanks so much for getting back to me - really appreciate it.

B

**Comment by codemonkeynorth** [comment]
@bentron2000  in your type definitions you can alternatively use

`setEgg: Action<StuffModel["nestedThing"], string>;`

then

```
nestedThing: {
    egg: '',
    setEgg: action((state, payload) => {
      state.egg = payload; 
    })
  },
```

seems to work fine, but note you can't set state outside of `nestedThing` this way

see my example https://github.com/ctrlplusb/easy-peasy/issues/611#issuecomment-2072809945
