### ISSUE TITLE
Make state be a primitive

### ISSUE THREAD

**Issue by raunofreiberg** [ctrlplusb/easy-peasy#17]
How can I make a model be a primitive, e.g `userNameModel` is just a `string` but I also want this model to have methods? I don't want to make an object with a separate property on it, this adds unnecessary boilerplate. E.g, accessing via `state.user` instead of `state.user.name`

**Comment by ctrlplusb** [comment]
I've had a think about this. At the moment you can't model actions against primitives - you would have to introduce a wrapping object as you noted.

To address this we could consider adding a new helper:

```javascript
import { createStore, value } from 'easy-peasy';
//                      👆 import the new helper

// Usage with a primitive
const userName = value(''); // 👈 declare the value, providing it's default
userName.toUpper = (x) => x.toUpperCase(); // 👈 add an action, you return the new value

const store = createStore({
  user: {
    userName, 👈 add the value to your model
    favouriteFruit: 'pear',
  }
})
```

But just because we should I am not convinced that we should. 😊

I'll leave this issue open and see if a discussion forms around it.

**Comment by raunofreiberg** [comment]
I did this as a workaround:

```
const userModel = {
    userName: 'Bob',
    changeName: (state, payload) => {
        state.userName = payload;
    },
}

const store = createStore({
    ...userModel,
});
```

This way I had the name accessible via simply `state.username`, although with the side effect of having all of the respective model actions available on the `dispatch` property.

**Comment by ctrlplusb** [comment]
Nice one. Happy to close this then.
