### ISSUE TITLE
2.4.0 and 2.5.0 selectors do not work

### ISSUE THREAD

**Issue by macrozone** [ctrlplusb/easy-peasy#208]
given this simple example:

```
 myprop: selector([(state, storeState) => {
   console.log("state and store state", state, storeState)
   return "fooo"
  }], args => {
    console.log('args', args)
    return 'bar'
  }),
```

when accessing this state, the first log from the args selector is logged, but the second is never called.

i am not sure what i am doing wrong. I tried both 2.4.0 and 2.5.0, both do not work

**Comment by macrozone** [comment]
ah i forgot to execute the selector.... :-(

a bit disapointing that you can't seamlessly switch between a state and a computed state as you could do with select before. Now when you switch between real state and computed state, you have to change every place where you access this state property. Solution could be that `usteStoreState` would execute selectors

**Comment by macrozone** [comment]
also this should have a big warning sign: https://easy-peasy.now.sh/docs/api/selector.html#simple-example

**Comment by ctrlplusb** [comment]
Dude, I feel ya. I hate that I had to move to function based selectors, with lazy execution. But without this I would open up users of this lib to performance footguns. I admit it doesn't feel as natural to use them, especially accessing the functions via `useStoreState`. 

I have tried thinking this over, and combining your idea we could consider not binding selectors via state, and instead introduce a new hook, `useStoreSelector`. Using this hook would grant you access to the selectors and will automatically execute them.

For example, given the following model:

```typescript
import { selector } from 'easy-peasy';

const model = {
  basket: {
    items: [],
    totalPrice: selector(/*...*/)
  }
}
```

The new hook would work as so:

```typescript
import { useStoreSelector } from 'easy-peasy';

function MyComponent() {
  const totalPrice = useStoreSelector(state => state.products.totalPrice);
}
```

And we could allow you to declare runtime args much cleaner too.

```typescript
import { useStoreSelector } from 'easy-peasy';

function MyComponent({ id }) {
  const product = useStoreSelector(
	state => state.products.getById, 
	[id]  // 👈 these become the runtime args
  );
}
```

Note how there is now no need to execute the selector.

This could also be implemented as a non-breaking change too. But I would probably consider marking the access of selectors via `useStoreState` as being deprecated as I want to keep the API surface area down to the minimal possible.  v3 of this lib will be a big one because it will be the API I want to long term commit to. So far I am very happy with the existing APIs, except for selectors. Like you they don't feel amazing, but I felt forced into the current design. With the above alternative they do become far more palatable.

One case still to be considered though is consuming selectors from each other. I may need to think of an alternative strategy there. One possible consideration would be to provide a 3rd parameter to the state resolver, which would be the selectors and then give this similar behaviour to the above, but I need to think this through. If we can come up with a nice API experience on this side too I would definitely start to consider this more.

**Comment by ctrlplusb** [comment]
Closing this, but planning on opening an RFC with a few proposals in the hope to get feedback. As soon as we can nail down a selector API that has a good balance of performance and DX I'll be happy to cut v3 of easy-peasy and focus on long term maintenance.

**Comment by ctrlplusb** [comment]
See #209 

I would really appreciate your critique on the proposal.
