### ISSUE TITLE
Interop with existing redux store

### ISSUE THREAD

**Issue by mcamac** [ctrlplusb/easy-peasy#222]
Hi there, great library! 

I read through the docs and found https://easy-peasy.now.sh/docs/recipes/usage-with-react-redux.html but the given example replaces the top level `Provider`'s store with a new easy-peasy store.

We've got an large existing redux store, and wanted to begin migrating to easy-peasy by having easy-peasy control a subtree of that store. Is that possible? Thanks!

**Comment by ctrlplusb** [comment]
Hey @mcamac 

Thanks! Stoked you dig it.

Yeah, it _could_ be possible to do this. Effectively, you would have to replace the `redux` version of `createStore` with the `easy-peasy` one. And then instead of `combineReducers` you can use the [`reducer`](https://easy-peasy.now.sh/docs/api/reducer.html) helper from `easy-peasy`.

_Before:_

```javascript
import { createStore, combineReducers } from 'redux';
import productsReducer from './reducers/products';
import basketReducer from './reducers/basket';

const rootReducer = combineReducers({
  products: productsReducer,
  basket: basketReducer
});

const store = createStore(rootReducer);
```

_After:_

```javascript
import { createStore, reducer } from 'easy-peasy';
import productsReducer from './reducers/products';
import basketReducer from './reducers/basket';

const store = createStore({
  products: reducer(productsReducer),
  basket: reducer(basketReducer),
  victory: {
    msg: 'Easy Peasy + Redux harmony ❤️',
    updateMsg: action((state, payload) => {
      state.msg = payload;
    })
  }
});

const store = createStore(rootReducer);

// Dispatch an easy peasy action
store.getActions().victory.updateMsg('Woot, dispatching an easy peasy action');

// Dispatch a standard redux action
store.dispatch({ type: 'ADD_TO_BASKET', payload: 1 });
```

As you would need to slowly migrate your `react-redux` connected components you will need to provide the store to the `Provider` from `react-redux` and the `StoreProvider` from `easy-peasy`.

```javascript
import { Provider } from 'react-redux';
import { StoreProvider } from 'easy-peasy';
import store from './store';

const dualApp = (
  <Provider store={store}>
    <StoreProvider store={store}>
      <App />
    </StoreProvider>
  </Provider>
);
```

The `createStore` from `easy-peasy` supports Redux middleware via the [config](https://easy-peasy.now.sh/docs/api/store-config.html).

This could all work in principal - if you didn't have some really exotic Redux middleware in play.

**Comment by ctrlplusb** [comment]
If you do go ahead I would love to hear your feedback on the experience. 👍

**Comment by allpro** [comment]
FYI, I'm testing this pattern right now. Shortly I'll be integrating some _normal_ reducers and actions. I'm going to try using a `reducerEnhancer` helper to 'combine' the two sets of reducers, with _no changes_ to the existing Redux code. IF this works as hoped, I'll post that helper here.

**Comment by allpro** [comment]
**I have successfully _integrated_ Easy-Peasy (EP) with ordinary Redux actions and reducers.** The method I used is a **reducerEnhancer**, which is a store-config option in EP. This helper (below) runs every action through _both_ the ordinary root-reducer (`rootReducer`) _and_ the EP root-reducer that's passed-in (`epRootReducer`) ...

```javascript
const reducerEnhancer = epRootReducer => (
    (prevState, action) => {
        let nextState = prevState
        nextState = rootReducer(nextState, action)
        nextState = epRootReducer(nextState, action)
        return nextState
    }
)

const store = createStore(model, {
    name: 'Test Store',
    reducerEnhancer
})
```

### Demonstration Repository

The **Easy-Peasy Test App** I created (using CRA) is on GitHub. If you want to do your own testing, pull it and then run `npm install` and `npm start`. Use **Redux Dev-Tools** to see what's happening when you click the test-buttons.
https://github.com/allpro/easy-peasy-tester

### combineReducers Issues

The ordinary rootReducer is created with the **combineReducers** helper. This can cause problems because **it ignores/deletes any top-level 'key' that does not exist in its own configuration**. This means keys that exist _only_ in EP models get deleted! combineReducers logs these keys in the console so it's easy to debug.

**The simple solution is to add _dummy-keys_ for domains/keys that exist only in EP.** This prevents combineReducers from deleting them. Here is what that looks like in my test app...

```javascript
const dummyReducer = state => state || {}

export default combineReducers({
    posts,
    albums,
    // Add dummy keys for Easy-Peasy root-keys.
    // This prevents combineReducers from ignoring/deleting these keys.
    list: dummyReducer
})
```

### Overlapping Functionality

I tested having the same data-keys, thunks and actions specified in _both_ EP and ordinary Redux. **This works fine.** Since the two instances use different action-names (by default), only one reducer is run for each action, so there is no duplication. However, EP _can_ dispatch an action-name to be handled by an ordinary reducer, and visa-versa. This means the two systems can inter-operate easily, and code can be transitioned to EP one action or reducer at a time.

### Middleware Issues?

EP already adds `redux-thunk` middleware, so if you are using this you don't even need to import it anymore! Other middleware can be added, but I didn't need to - yet.

My _next test_ will be with Redux Saga middleware because that's what I need to integrate with. I'm hopeful that will not be a problem. Stay tuned!

**Comment by ctrlplusb** [comment]
Really novel approach @allpro 👍

Thanks for sharing.

**Comment by ctrlplusb** [comment]
Added to v3 docs

**Comment by mcamac** [comment]
Thank you both!
