### ISSUE TITLE
State update on an unmounted component when using thunks

### ISSUE THREAD

**Issue by valstu** [ctrlplusb/easy-peasy#306]
I bumped into on issue where easy-peasy tries to make state update on a component which is unmounted. This happens when I'm using thunks to perform side effects which will trigger actions. Then I am using that state to define what components to render.

For the sake of simplicity I created this simple Codesandbox example.
https://codesandbox.io/s/festive-moore-9fjvz

I have a store which has `userId`. If the userId is undefined it will render `<Login />` component, otherwise it will render the `<Home />` component. Home component consumes the `userId` state and `logout` thunk. When you first click login button on Login component it renders the `<Home />` component as expected. Then if you click the logout button on the <Logout /> component the state is updated correctly and React renders the `<Login />` but it still apparently tries to update the state inside the Home component even though it is unmounted. You will notice the following React warning on the console.
```
Warning: Can't perform a React state update on an unmounted component.
```

This won't happen if I change the onClick on the logout button to `loggedOutSuccess` action instead of `logout` thunk.

**Comment by jmalins** [comment]
I observed this as well when an asynchronous state update causes a component using `useStoreState` to be unmounted.

Wading through the stack trace, it appears that the state update in question is the call to `forceUpdate({})` (aka the s+1 simple reducer) in `checkMapState`.

**Comment by TatisLois** [comment]
Were you able to resolve this warning?

**Comment by jmalins** [comment]
Yes, I was, thanks for reminding me to post the results.

See PR #324 for fix and explanation.

**Comment by ctrlplusb** [comment]
Fixed in v3.1.0

Thanks to @jmalins for the fix. 👍

**Comment by AnsonH** [comment]
I suggest re-opening this issue since using **v5.2.0** will cause the same warning of "state update on an unmounted component":

https://user-images.githubusercontent.com/57580593/211547827-d8e127eb-5d88-49ff-b611-73ffa3fbbd32.mp4

Here's the Code Sandbox link (same code as the original sandbox, but with v5.2.0).

[![Edit Easy Peasy #306 in v5.2.0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/easy-peasy-306-in-v5-2-0-tt1vtf?fontsize=14&hidenavigation=1&theme=dark)

I tried changing the version to v3.1.0 and the warning does NOT appear. It seems that some updates along the way re-introduced this bug.

**Comment by jmyrland** [comment]
Thanks for the sandbox @AnsonH - I'm reopening this issue so we can investigate this further.

**Comment by jmyrland** [comment]
It seems that this issue has been resurrected by supporting React 18 (#769) by utilizing the `useSyncExternalStoreWithSelector` internally. Because of this, we do not have access to the lifecycle anymore to do "mount"-checks (as we did previously). 

I'm inclined to think that `useSyncExternalStoreWithSelector` does some clever stuff behind the scenes for handling subscriptions (as indicated [here](https://github.com/reactwg/react-18/discussions/86)), given that the issue only occurs once in the provided sandbox when logging in/out multiple times within a session.

I've not found anyone else having this issue using this hook, but I've found that they are [removing the specific error because it is misleading](https://github.com/reactwg/react-18/discussions/82).

Currently I do not see a workaround for this issue for React 17, without removing React 18 support.
