### ISSUE TITLE
How should we listen to a thunk successType and failType?

### ISSUE THREAD

**Issue by viniciusHagamenon** [ctrlplusb/easy-peasy#347]
Hi!

I'm trying to listen to `successType` and `failType` from an `thunk` but the `failType` is only dispatched if I don't catch the error from the original thunk but doing that I get uncaught exceptions as it's being re-thrown by the `thunk`.

Is there a way to trigger a `failType` without getting exceptions?

I have looked at the code and thought that maybe we could do something like this in the thunks.js:

```js
try {
      const result = references.dispatch(() => thunkHandler(payload));
      if (typeof result === 'object' && typeof result.then === 'function') {
        return result
          .then(resolved => {
            dispatchSuccess(resolved);
            return resolved;
          })
          .catch(err => {
            dispatchError(err);
            if (!isSomethingListeningToThisThunkFailType) { // <
                throw err;
            } // <
          });
      }
      dispatchSuccess(result);
      return result;
    } catch (err) {
      dispatchError(err);
      if (!isSomethingListeningToThisThunkFailType) { // <
          throw err;
      } // <
    }
```

Thanks for the lib by the way, it's awesome!

**Comment by Schiavi** [comment]
This is somewhat related to #332, because the intention of this is to have a global error handler for thunks.

We are trying to avoid the Redux pattern of `ACTION` > `ACTION_SUCCESS` || `ACTION_FAIL` by using easy-peasy success/fail types. The problem is that the success always happens if we catch the thunk error inside the thunk, and we cannot let the thunk throw because it's not a silent fail.

**Comment by ctrlplusb** [comment]
The v4 release will include some notes that addresses this issue. Stay tuned.
