### ISSUE TITLE
Add support for `mockActions` and `getMockedActions()` in `createContextStore`

### ISSUE THREAD

**Issue by ayush987goyal** [ctrlplusb/easy-peasy#364]
As the title says, `createContextStore` can have similar mocking functionalities as `createStore`.

**Comment by ctrlplusb** [comment]
I have some ideas for an update to the `createContextStore` which will inherently provide you with this capability. Stay tuned.

**Comment by ctrlplusb** [comment]
Unfortunately due to the current design I am unable to satisfy this request. It would need some redesign around the semantics of the API.

TBH, I prefer not to be overly fussed with testing implementation details anyways. I prefer using React Testing Library along with msw (Mock Service Worker) and then do more integration type tests on my components. If you haven't already, please do give this style a try. 

Sorry if this isn't what you were hoping for.
