### ISSUE TITLE
Access root storeState from within an action?

### ISSUE THREAD

**Issue by oller** [ctrlplusb/easy-peasy#401]
Hi there, is this possible or the beginnings of an anti-pattern?  I've an abstraction of a store module, which derives permissions from various state properties across multiple store modules using computed properties.

I'm currently getting the storeState and passing that as part of the payload to the action, but that feels a rather bloated way to go about achieving this.  I just need to access the state of other modules for some logic in order to have the action set the correct state.

Many thanks for a great library which was a breeze to integrate!

**Comment by ctrlplusb** [comment]
Hi @oller 👋

Glad to hear you are enjoying it. 💜

You could do exactly this if you created a thunk to access state and then delegate to actions in order to perform the necessary.

The [docs on thunks](https://easy-peasy.now.sh/docs/api/thunk.html) should provide you with all the info you need here. 👍

Shout if anything is unclear.

**Comment by oller** [comment]
Ah I was heading towards that conclusion, but that makes a lot of sense now and was very concise to implement.   Now to get my head around `actionOn` and `thunkOn` 🤓 . Thanks again for such a cracking lib and the prompt response.
