### ISSUE TITLE
redux, redux-thunk, immer as peer-dependencies

### ISSUE THREAD

**Issue by VinSpee** [ctrlplusb/easy-peasy#41]
HI! I'm digging easy-peasy. I'm curious as to why redux, redux-thunk, and immer are hard dependencies, but react is a peer-dependency. Could you gain some flexibility with existing redux projects by making them peerDeps instead?

**Comment by ctrlplusb** [comment]
Hey @VinSpee!

Glad to hear.

I am honestly not sure about this one. I initially decided to make them explicitly dependencies in order to reduce the amount of "work" required to get your store working.

The flexibility you desire - is it because you are trying to migrate an existing application to `easy-peasy`? Could you give me some insight into the friction that you are experiencing that lead to you opening this issue.

Thanks

**Comment by VinSpee** [comment]
Exactly right. I work on a large app and want to use easy-peasy for one feature to start. 

Honestly I’m not sure how it will “shake” out in the build - maybe webpack is smart enough not to duplicate it? Doubtful. 

Also I do understand the desire to have an “install and go” setup. On packages where I have peerdeps, I recommend people use `npx install-peerdeps` to make it easier.

**Comment by ctrlplusb** [comment]
I don't think it will be an issue, especially if you are on the same major version. Have you tried running [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) on your build output. Also worth inspecting your resolved node_modules.

**Comment by ctrlplusb** [comment]
Closing this for now. Please let me know what your experience was like, and we can reopen if needed. 👍
