### ISSUE TITLE
[Question] How to test `createComponentStore`?

### ISSUE THREAD

**Issue by JeromeDeLeon** [ctrlplusb/easy-peasy#423]
I was able to pass other tests but when the test includes calling from `thunk` to `action` where the action mutates the `state`, the test failed.

I wasn't able to fail the test manually but when programmatically creating test, `setFormError` was not being called inside `signinUser` and therefore the test failed because `formError` was expected not to be `undefined` and also `setFormError` was expected to be called.

```js
// store
const signinModel = {
  formError: undefined,
  setFormError: action((state, error) => {
    state.formError = error;
  }),
  signinUser: thunk(
    async (
      { setFormError },
      { username, password },
      { injections: { userService } },
    ) => {
      try {
        await userService.signinUser(username, password);
      } catch(error) {
        setFormError(error?.message);
      }
    },
  ),
};

// test
test("should not sign in user when it's not valid", async () => {
  const signinFormValues = {
    username: 'admin',
    password: 'admin123',
  };

  const useStore = createComponentStore(signinModel, {
    injections: {
      userService: {
        signinUser: jest.fn(() => Promise.reject(new Error('Error'))),
      },
    },
  });

  const { result } = renderHook(() => useStore());
  const [state, actions] = result.current;

  const setFormError = spyOn(actions, 'setFormError');

  act(() => {
    actions.signinUser(signinFormValues);
  });

  expect(setFormError).toBeCalled();
  expect(state.formError).toEqual('Error');
});
```

**Comment by ctrlplusb** [comment]
Hi @JeromeDeLeon;

I would test a component using a local store the same way I would test a component using the native React hooks (`useState`, `useEffect`, ...) - via [React Testing Library](https://testing-library.com/docs/react-testing-library/intro).

Basically you would render/mount the component and mock the user service.

I prefer this approach for components as you are testing the underlying behaviour rather than the implementation. You could decide one day that you hate Easy Peasy (or move away from the deprecated `createComponentStore` to `useLocalStore`) and your tests should in theory still work.

Hope that helps. 💜

**Comment by JeromeDeLeon** [comment]
Thank you so much.
