### ISSUE TITLE
Be able to provide a parameter to selector at runtime

### ISSUE THREAD

**Issue by mickmister** [ctrlplusb/easy-peasy#44]
I'm trying to make a `getTodo` selector that selects a specific todo from the store by passing in the todo's id into the selector. Here's a hypothetical example:

```typescript
const store = createStore({
  todos: {
    items: [
      {id: 1, text: 'Todo 1'},
      {id: 2, text: 'Todo 2'},
    ],
    getTodo: select((state, id) => {
      // some logic I don't want to duplicate here

      return todo
    }),
  },
})

function TodoText(props) {
  const {todo_id} = props
  const todo = useStore(state => state.todos.getTodo(todo_id))

  return <span>{todo.text}</span>
}
```

The current implementation of selectors expose the results through properties instead of method calls. Adding the proposed functionality would change this pattern. I'm also not sure how this would fit within configuring the store.

Is this problem something that can be easily solved already, without introducing code changes? One solution is to import a function that can perform the computation, and have the component pass the current state into it to compute the result, but I think it would be more convenient to have the functionality attached to the store directly. Any thoughts?

**Comment by ctrlplusb** [comment]
Hey @mickmister,

I gave this a think and one approach would be to return memoized functions from your select.

Imagine a typical "getById" selector, you could satisfy the following definition:

```
select(state => id => result)
```

So instead of your `select` returning state it returns a nested selector.

You can then utilize the `memoize-one` library (already a dependency of `easy-peasy`) to ensure that memoization occurs on your nested selector.

This would result in the following implementation:

```javascript
import { createStore, select } from "easy-peasy";
import memoizeOne from "memoize-one";

const model = {
  todos: {
    items: {
      1: "Foo",
      2: "Bar"
    },
    byId: select(state => memoizeOne(id => state.items[id]))
  }
};

const store = createStore(model);

console.log(store.getState().todos.byId(1)); // Output: Foo
console.log(store.getState().todos.byId(1)); // Memoised Output: Foo
```

NOTE!!

Trying to implement this exposed an issue with the internals. I had to publish a new version (`easy-peasy@1.7.1-alpha.0`). This new version appears to work as expected.

I've also created a codesandbox illustrating this. Have a try out and then we can consider publishing this alpha as latest at some point.

https://codesandbox.io/s/6w5y3yjw2n 

Click the "Console" button at the bottom of the sandbox to see the output.

**Comment by mickmister** [comment]
Sounds great, I really like the explicitness this way. I'm so glad you've solved how it can fit within the system! Loving the library!

**Comment by ctrlplusb** [comment]
FYI, this has landed in 1.7.1 👍

We should consider adding this info to the tips and tricks section though.

**Comment by ctrlplusb** [comment]
Been thinking and one option would be to extend our `select` API, so that if it receives a function back then it automatically memoizes it.

**Comment by mickmister** [comment]
As far as changing the API, making the user manually call `memoizeOne()` makes it less `easy-peasy` to develop the store (more boilerplate), so I am on board for the implicit memoizing.

While this is on discussion, can you think of any pitfalls that might occur if the user incorrectly uses the selector, making the memoization cache a result that actually needs to be recomputed? Say some selector depends on an external resource like `sessionStorage`. If I were to create a dependency function that accesses `sessionStorage`, would the memoization be successfully computed based on the current state of `sessionStorage`? I haven't (thoroughly) dug into the select API implementation so I'm not exactly sure how the dependency array works.

> We should consider adding this info to the tips and tricks section though.

I'd be happy to help with PRs here.

**Comment by DmacLoyaltyOne** [comment]
@ctrlplusb How would we implement this in typescript? 

Right now I've got 
```
interface OffersModel {
  regionalOffersTranslated: Select<OffersModel>
}
const offers: {
// selectors
regionalOffersTranslated: select(state => languageSelector => {
  ...
})
}
```

```
const getRegionalOffersTranslated: any = useStore(state => state.offers.regionalOffersTranslated)
const offers = getRegionalOffersTranslated(languageSelector)

```

But if I want to return a function with a language string to select, it breaks (typescript?). Any ideas?

Getting the following error:

Error: Memoizerific functions should always be called with the same number of arguments

**Comment by ctrlplusb** [comment]
Hey @DmacLoyaltyOne;

You need to type the return of your `Select`.

For example.

```typescript
interface Notification {
  id: string;
  title: string;
}

interface Notifications {
  [key: string]: Notification;
}

type GetNotificationById = (id: string) => Notification | void;

export interface NotificationsModel {
  items: Notifications;
  add: Action<NotificationsModel, Notification>;
  getById: Select<NotificationsModel, GetNotificationById>;
}

const notificationsModel: NotificationsModel = {
  items: {},
  add: action((state, payload) => {
    state.items[payload.id] = payload;
  }),
  getById: select(state => (id: string) => state.items[id]),
};
```

And then you could use it:

```typescript
store.dispatch.notifications.getById('xyz123');
```

**Comment by DmacLoyaltyOne** [comment]
@ctrlplusb Thanks for that, I appreciate it.

The problem was actually a javascript error though, as I mentioned in the update.
Maybe consider documenting that for a selector, since it's somewhat of a 'gotcha'

For instance, if I wanted to getById inside of a React component, would I not have to implement it in the following way?

```
const notifificationById = useStore(state => id => state.notifications. getById(id))
```
However, this does not seem to work properly. I get an error saying it is not a function when I try to invoke it.

If I simply write :
```
const notifificationById = useStore(state =>state.notifications. getById)
```
I get the error: Error: Memoizerific functions should always be called with the same number of arguments

**Comment by ctrlplusb** [comment]
Hey @DmacLoyaltyOne;

Thank you for that clarity. 

🤔

That seems like a bug. I certainly wouldn't expect to have to do that.

I will look into it as soon as I can.

Thanks for the report.
