### ISSUE TITLE
Migrate to TypeScript?

### ISSUE THREAD

**Issue by nainardev** [ctrlplusb/easy-peasy#476]
*No description provided???*

**Comment by ctrlplusb** [comment]
Whilst I am a TypeScript convert my current stance is that it is more useful for large applications rather than libraries. I like that I can be a bit crazier with the internals without having to appease a type system. Then I just ship typings that box it quite nicely and only represent the public API. ☺️

**Comment by nainardev** [comment]
Atleast this has type™ defenitions?
