### ISSUE TITLE
Call a store from another store

### ISSUE THREAD

**Issue by vladwulf** [ctrlplusb/easy-peasy#525]
Hello, 

I really love working with easy-peasy but I struggle to implement some patterns I would love to see.
I want to call an action of user store from the post store. using getStoreActions

![image](https://user-images.githubusercontent.com/7473791/88597005-3735d700-d05e-11ea-95aa-2a0e87da08d6.png)

So I have two stores
```
export interface Model {
  posts: PostsModel;
  user: UserModel;
}

const model: Model = {
  posts: postsModel,
  user: userModel,
};
```

The user store has toggleLoader() function that shows a loading modal. I need to show it when a request is done to the server for slow connections.

``` 
toggleLoader: action((state) => {
   state.showLoader = !state.showLoader;
 }),
```

This is the error I have 
![image](https://user-images.githubusercontent.com/7473791/88596659-7b74a780-d05d-11ea-8eee-6f7cfe9d77c4.png)

It seems quite logical for me that I can call a store from another. That will avoid a lot of non reusable code in the components

**Comment by jchamb** [comment]
@vladwulf i Personally haven't used the types, but at a glance from a standard JS perspective that should work, so makes me think your typing is incorrect.

https://easy-peasy.now.sh/docs/typescript-api/actions.html has an example of basically what you are doing. May be worth reviewing to see if you have something off.

**Comment by vladwulf** [comment]
@jchamb  My problem is that I want to call an action of store A from store B. I am not sure what i'm doing wrong. Right now i merged all stores into one and that works but of course it's not feasible for any big/serious project.

**Comment by jchamb** [comment]
Sorry maybe I'm missing understood I assumed your example was your current working code that was failing. When you say "stores" you mean two completely separate `createStore` calls eg:
```
const A = createStore({ ... });
const B = createStore({ ... });
```

If that is what you are doing then that won't work based on your example above. Each store is its own context so it would not have cross reference. If **A** is truely created before be though, theres no reason should not be able to do something like `A.getActions().model.myAction(payload)` inside of **B**. This sort of pattern seems like a circular dependency nightmare though.

I'm curios what you mean by big/serious project? I have an app with 40ish models and a single store has never been an issue. We use a combo of namespace groupings along product lines and rather than directly loading every model on boot we use a combination of react-loadable and `store.addModel()` to initialize parts of the store only when required by the app.

Splitting into models is basically the same pattern as separate reducers in a typical redux app with `combineReducers`. As far as i'm aware if you had separate redux stores your would have to manually dispatch directly from each store as well.

**Comment by vladwulf** [comment]
No I was using the same store.

So I made additional tests and it appears that the problem comes from the fact that when we use typescript it does not find a call signature for the Thunk.

Assuming you have an app model
![image](https://user-images.githubusercontent.com/7473791/89693934-f6fd1100-d907-11ea-9fcf-1e1560e2a4d9.png)


And assuming you have a user model that needs to call the app model
![image](https://user-images.githubusercontent.com/7473791/89693954-0714f080-d908-11ea-92c1-716116e991d1.png)


So the problem is that we don't have a call signature for the thunk I am trying to call.
I don't have a sufficient knowledge in typescript to fix it.

**Comment by vladwulf** [comment]
You can look at it yourself.
I have created a repo with js source where it works https://github.com/vladwulf/ep-bug-js 

And a repo with the same code in ts where you have a bug if you uncomment the lines in the user.store.ts 
https://github.com/vladwulf/ep-bug-ts

**Comment by vladwulf** [comment]
Okay issue is solved.
I misunderstood some things but this example helped.
https://codesandbox.io/s/easy-peasytypescript-tutorialtyped-thunk-global-870xx?file=/src/model/todos.ts

Basically my triggerUserAction thunk needed to have this signature: Thunk<this, undefined, undefined, RootModel>.
This would inject the global model definition types into the thunk action mapper.

**Comment by jchamb** [comment]
Glad you got it resolved. If there is any document info you think needs added for better examples on the docs for the typescript types I would def encourage a PR!

**Comment by arbuzaicer** [comment]
If this case is still in progress and someone is looking for an answer - you just need to wrap your model into easy-peasy's Actions generic

```
someAction: thunk(async (actions, payload, helpers) => {
    try {
      const storeActions = helpers.getStoreActions() as Actions<StoreModel>; // Actions is import type from easy-peasy, just put your store model here and you get all your reducers
    }
}),
```
