### ISSUE TITLE
What is the Reducer Value in chrome dev tools component Tabs?

### ISSUE THREAD

**Issue by sirajalam049** [ctrlplusb/easy-peasy#538]
So I was optimizing my application and just saw that my root was re-rendering whole no prop or state or hooks were updating. But in the Profile tab of chrome showing that the re-rendering because the hooks were changing.

Then I saw something unusual.

![image](https://user-images.githubusercontent.com/22110988/90453016-23d1d500-e10d-11ea-97b9-ed95bea27524.png)

I was selecting two variables using the useStoreState hook, none of them were changing but still component was re-rendering. Then I saw the highlighted Reducer value which is showing 100, was changing twice.

So what is that value? How can I stop from changing its value?

After digging into the codes, I found that 
https://github.com/ctrlplusb/easy-peasy/blob/6ea97dac7382f4b677fc8315ce39039a7b3641f6/src/hooks.js#L78-L80

This piece of code causing the value change (increment) and **force** re-rendering the whole component. There's no comment regarding that, why is that done?

**Comment by ctrlplusb** [comment]
Ooof, big question about the internals. 😅

This pattern is intentional based on the design of hooks and the semantics that we need to ensure in regards to this library. The `react-redux` library follows a similar approach. In fact, our implementation is largely influenced by theirs.

There are also other points about double execution with React's hooks when in dev mode.

I am pretty swamped so can't get into this right now, but I'll initially say that you shouldn't worry about these additional renders. Likely there is no impact to your application performance.

Hopefully I can address this in a bit more detail for you in the future. 🙏

**Comment by ctrlplusb** [comment]
Sorry, in a nutshell, it is because within our `useStoreState` hooks we are subscribing to the redux store directly. Therefore store updates are outside of the react lifecycle. To ensure that our hook returns back the newly resolved state we have to use the forceRender trick to ensure the component re-renders with the newly mapped state.
