### ISSUE TITLE
How to compose actions?

### ISSUE THREAD

**Issue by Revilotom** [ctrlplusb/easy-peasy#600]
I would like to reference actions from within other actions, do I need to use a thunk for this?
Since its purely synchronous code I would like to avoid using a thunk if possible..

**Comment by jchamb** [comment]
What's your reasoning for not wanting to use a thunk? There is not any downside there.

**Comment by Revilotom** [comment]
Simply that when I hear "thunk" I think of asynchronous code and when I hear "action" I think of synchronous code and I want to preserve that separation.

**Comment by LuisOsta** [comment]
So that's not really what differentiates a thunk from an action. Actions are supposed to be atomic. So it doesn't make sense in the action reducer system to allow them to dispatch other actions.

If you don't want to use thunks to dispatch multiple actions (which can cause issues).
I would recommend creating an action that can update all of the state variables you need at once.


What is the specific use case you have?

**Comment by Revilotom** [comment]
Ahh okay they are supposed to be atomic! That makes a lot of sense!

Why would dispatching multiple actions within a thunk cause issues? 

The use case is that I have a a search bar component with an action that sets the state to "isLoading". I also have another action that sets the search term. I wanted to reuse the loading action when defining the search term action in order not to repeat myself.. There are other actions beside setting the search term that would cause the state to be loading so thats why I wanted separate actions.

**Comment by LuisOsta** [comment]
So let's say that you have a thunk that calls two actions:
- Action A
- Action B

Action A runs successfully but Action B throws an error or fails in some way. If this thunk calls actions are that deeply related to each other. (ie both states depend on each other). You'll have inconsistency in the state.

What you should have to do is either a try-catch or some kind of error check to reset the state if any of them fail. Which gets pretty complicated pretty quickly.

I think this issue was mentioned in the docs but I can't find it anymore

**Comment by jchamb** [comment]
@LuisOsta I was also curious what you meant there. Def a valid point but I would say thats more in the design approach/flaw arena and not really a general multiple action calls flaw, but to each their own.

@Revilotom I've used that pattern in multiple smaller apps, and haven't had issues with it. I typically prefer to use the thunkOn listeners to trigger things like loading state though.

https://easy-peasy.now.sh/docs/api/listeners.html

I will say that would def agree with @LuisOsta if your doing anything beyond toggles your better off not layering multiple actions in a thunk and keeping them as singular in responsibility as possible.

**Comment by LuisOsta** [comment]
Oh, I definitely agree with you @jchamb that you shouldn't want to handle a loading state like that. Honestly, I would keep that locally. My point is more of an issue if, for instance, you're querying for a user's profile and instead of calling one action to update all of them, you have an action for each property that you get back from the server.

You are right that it's not really a bug/issue as more of an approach to store design. Just something that's been a pain from the projects I've done.

There's a variety of ways you can handle the loading state when using hooks. That's not the kinda thing you wanna store in the local state.

**Comment by LuisOsta** [comment]
@Revilotom Does that solve the issue/quandary you were having? Or do you think there's a better/different approach?

**Comment by Revilotom** [comment]
Thanks for the replies everybody!

@LuisOsta Well I can see now why actions should be atomic but I still don't like having to repeat myself a lot haha. 
I dont have any ides for a better approach either....

Lets say I have an action like this:

```
    setTerm: action<SearchModel, string>((state, payload) => {
        state.queryParameters._term = payload
        delete state.queryParameters._wordId
        state.hasMore = true
        state.pageCount = 0
    }),
```
However in 3 other actions I would also like to do:

```

        state.queryParameters._term = payload
        delete state.queryParameters._wordId
        state.hasMore = true
        state.pageCount = 0

```

What should my implementation be then, should I repeat myself 3 times ?
As you said there could be issues if I use a thunk... 
Im not sure, I just feel like my code is getting less and less maintainable...

**Comment by LuisOsta** [comment]
@Revilotom Why can't you just call the one action in all of the places where you need it? Can you tell me more about the context in which you use it? I think there's a way for you to not have to make 4 actions that do the same thing and still have the atomic actions

**Comment by jchamb** [comment]
@Revilotom a code sandbox would prob help visualize what you have going a little better. It's hard provide advice on an application flow we can't see.

**Comment by LuisOsta** [comment]
Yeah a code sandbox example would be immensely helpful

**Comment by Revilotom** [comment]
Thanks for your help! After rereading the previous replies I have worked out how I should be using atomic actions, I dont think I need to keep the issue open so I'm going to close it!
