### ISSUE TITLE
Create a Good First Time Issue Label & Contributing.md

### ISSUE THREAD

**Issue by LuisOsta** [ctrlplusb/easy-peasy#603]
I think it might be helpful to those hoping to contribute to the project to make it clear what issues might be good for a first-time contributor to help with. The current labels, although good, don't make that too clear.

On a similar note, a CONTRIBUTING.MD file that describes how to set up the development environment for easy peasy and how to make contributions, in general, would be helpful (a good example of one would be the Testing Library [CONTRIBUTING.MD](https://github.com/testing-library/react-testing-library/blob/master/CONTRIBUTING.md)

**Comment by aashu0148** [comment]
hey i want to contribute how can i?

**Comment by LuisOsta** [comment]
I think that's more of a question for @ctrlplusb

**Comment by ctrlplusb** [comment]
Hi @LuisOsta 

Thank you very much for raising this. I have taken some time off maintaining Easy Peasy due to personal reasons.

I would love to keep Easy Peasy at a constant rate of maintenance though. I'll give the current labels a thought over and come up with a strategy to allow for this.

I'll make sure to get the contributing guidelines together too.
