### ISSUE TITLE
Cannot use computed properties with a function when doing SSR

### ISSUE THREAD

**Issue by ricardomatias** [ctrlplusb/easy-peasy#676]
When using easy-peasy with server side rendering, the store gets serialized and if there are computed properties which include a function as seen in the following example from the docs, there's an error because the store cannot be serialized due to a Getter function:

```js
 getById: computed(state =>
    // 👇 return a function that accepts an "id" argument
    id => state.items.find(product => product.id === id)
  )
```

**Comment by GollyJer** [comment]
I just ran into a similar problem with local persistence instead of SSR. 
With persistence turned on the app throws `Error in useStoreState: state.assets.getStakedAssetsByAddress is not a function.`.

It is a computed property with a runtime argument.
```javascript 
getStakedAssetsByAddress: computed(
  (state) => (address) => Object.values(state.stakedAssetsById[address]) || []
),
```

This exact issue was tackled in v4. https://github.com/ctrlplusb/easy-peasy/issues/503
Could there be a regression in v5?

**Comment by ctrlplusb** [comment]
What version of Node are you using?
