### ISSUE TITLE
undefined store on "contextmenu" event 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [ctrlplusb/easy-peasy#784]
This may be a bit specific to a certain use-case / library, but figured I'd report it anyway. If you check out [this codesandbox](https://codesandbox.io/s/goofy-breeze-652184?file=/src/App.tsx) and right click anywhere in the "Euros" column header or context menu, easy-peasy throws an error due to the store being undefined. 

![image](https://user-images.githubusercontent.com/18563015/197286177-206ed35d-c68f-40a5-a466-b1be2e35d822.png)

The error comes from the `<Foo />` component which consumes store state via the `useStoreState` hook. I can easily work around this by just passing in the state I need, but found this interesting.

The context menu is rendered inside a portal, and I thought maybe this has something to do with it, but its odd that its only on the "contextmenu" event that this seems to happen. Otherwise, the component is working fine and is clearly subscribed to the store. 

Any ideas?

Thanks!

**Comment by jmyrland** [comment]
Inspecting the code using React Dev Tools, it seems that the context is "lost" because the `ContextMenu` is rendered as a sibling of `App`:
![image](https://user-images.githubusercontent.com/837651/197543699-808099db-3e9b-4998-94e2-1a1c4d38a133.png)

The `ContextMenu` does not contain any `StoreProvider`, which in turn makes the `useStoreState` hook throw an error.

I was able to make it work by re-wrapping `<Foo />` with a new provider, **but with the same store**:
```diff
                menuRenderer={() => {
                  return (
+                   <StoreProvider store={store}>
                      <Foo />
+                   </StoreProvider>
                  );
                }}
```

![chrome_0HZafwmD6A](https://user-images.githubusercontent.com/837651/197542791-f36043b1-e3ba-4742-a64c-60084cba475e.gif)

Hope that helps 👍

**Comment by no-stack-dub-sack** [comment]
Ah, so when its rendered via a left-click it's still within `App`'s tree, but when you right-click it sits alongside `App` which explains why `store` seemed to only be undefined on right-click. This helps, thanks @jmyrland.
